from subprocess import check_output
from tabulate import tabulate


def wifi_name():
    command_show_wifi = "netsh wlan show profile"
    network_command = check_output(command_show_wifi, shell=True, text=True)
    profile_data = network_command.split("\n")
    for profile in profile_data:
        if "All User Profile" in profile:
            name = profile.split(":")
            wifi_password(name[-1].strip())


def wifi_password(name):
    command_show_wifi_pass = r'netsh wlan show profile' + ' "' + name + '" ' + 'key=clear'
    password_command = check_output(command_show_wifi_pass, shell=True, text=True)
    password_data = password_command.split("\n")
    for password in password_data:
        if "Authentication         : Open" in password:
            total_data[name] = "no password"
        if "Key Content" in password:
            password = password.split(":")
            total_data[name] = password[-1].strip()


def main():
    global total_data
    total_data = {}
    wifi_name()
    out_table = tabulate(total_data.items(), headers=['Wifi name', 'password'], tablefmt='pretty')
    print(out_table)
    write_to_file(out_table)
    input("[+] Press any key to exit.....")


def write_to_file(out_table):
    print("[+] Writing to a file.....")
    with open("wifi passwords.txt", "a") as wifi:
        wifi.write(credit_text)
        wifi.write('\n'+out_table)


def credit():
    global credit_text
    credit_text = """
               SAVED WIFI PASSWORDS

     ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
    ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
    ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
    ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
    ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
    ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
      ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
      ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
       ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p\n
    """
    print(credit_text)


try:
    credit()
    print("[+] searching for wifi passwords...")
    main()
except KeyboardInterrupt:
    print("\n[-]Exiting..........")
