from subprocess import check_output


def wifi_name():
    command_show_wifi = "netsh wlan show profile"
    network_command = check_output(command_show_wifi, shell=True, text=True)
    profile_data = network_command.split("\n")
    for profile in profile_data:
        if "All User Profile" in profile:
            name = profile.split(":")
            wifi_password(name[-1].strip())


def wifi_password(name):
    command_show_wifi_pass = r'netsh wlan show profile' + ' "' + name + '" ' + 'key=clear'
    password_command = check_output(command_show_wifi_pass, shell=True, text=True)
    password_data = password_command.split("\n")
    for password in password_data:
        if "Authentication         : Open" in password:
            total_data[name] = "no password"
        if "Key Content" in password:
            password = password.split(":")
            total_data[name] = password[-1].strip()


def main():
    global total_data
    total_data = {}
    wifi_name()
    print("+ {:-<30} + {:-<20} +".format("-", "-"))
    print("| {:<30} | {:<20} |".format("wifi names", "passwords"))
    print("+ {:-<30} + {:-<20} +".format("-", "-"))
    for nam, pas in total_data.items():
        print("| {:<30} | {:<20} |".format(nam, pas))
    print("+ {:-<30} + {:-<20} +".format("-", "-"))
    write_to_file()
    input("[+] Press any key to exit.....")


def write_to_file():
    print("[+] Writing to a file.....")
    with open("wifi passwords.txt", "a") as wipa:
        wipa.write("""
                      SAVED WIFI PASSWORDS
        
         ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
        ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
        ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
        ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
        ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
        ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
          ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
          ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
           ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p
        """)

        wipa.write("\n+ {:-<30} + {:-<20} +\n".format("-", "-"))
        wipa.write("| {:<30} | {:<20} |\n".format("wifi names", "passwords"))
        wipa.write("+ {:-<30} + {:-<20} +\n".format("-", "-"))
        for nam, pas in total_data.items():
            wipa.write("| {:<30} | {:<20} |\n".format(nam, pas))
        wipa.write("+ {:-<30} + {:-<20} +\n".format("-", "-"))


def credit():
    print("""
               SAVED WIFI PASSWORDS""")
    print("""
 ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
  ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
  ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
   ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p
""")


try:
    credit()
    print("[+] searching for wifi passwords...")
    main()
except KeyboardInterrupt:
    print("\n[-]Exiting..........")
